### ISSUE TITLE
Support scrolloff

### ISSUE THREAD

**Issue by Matts966** [utubo/vim-auto-hide-cmdline#2]
Thank you for this great plugin! :)
I would like to share my problem.

If we `set scrolloff=999` for example, we always see the up and down of cursor lines when the command line opens.
It would be great to temporally `set scrolloff&` when setting `cmdheight=1`.

**Comment by utubo** [comment]
~~Sorry, I can't simply fix this.~~
~~Because after user set scrolloff with cmdline (e.g. `:set scrolloff=5`),~~
~~this plugin will reset scrolloff (e.g.`let &scrolloff=999`).~~
~~So, user will not be able to set scrolloff with cmdline.~~

~~I'll see if I can think of a better way.~~

I will fix this in the near future!

thank you.

**Comment by Matts966** [comment]
Works perfectly!
Thank you :)
